### ISSUE TITLE
Add stripMargin and triple-quotes string support

### ISSUE THREAD

**Issue by svitkovsergey** [kaizen-solutions/virgil#71]
Hi,
Thanks for a great library!
If possible, I'd like to request a feature with triple-quotes cql-interpolated strings support & stripMargin method for cql-interpolated strings.

Why? 
Because it would be really helpful when creating tables via virgil, now it requires a lot of strings concatenation.

**Comment by calvinlfer** [comment]
Hey good thinking, I believe triple quotes are already taken care of, so I'll add stripMargin

**Comment by calvinlfer** [comment]
Released in 0.9.4 for zio1/zio2

**Comment by svitkovsergey** [comment]
Thank you so much!
